// 'use client';
import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'My First Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const res = await fetch('http://localhost:9999/topics', {
    caches: 'no-store',
  });
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
          {/* <li>
            <Link href="/read/1">html</Link>
          </li>
          <li>
            <Link href="/read/2">css</Link>
          </li> */}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <button type="button">delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
