// 'use client';
import Link from 'next/link';
import './globals.css';
import { Control } from './Control';

export const metadata = {
  title: 'My First Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL + '/topics', {
    cache: 'no-store', // topics - 리스트 업데이트시켜주기
  });
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
